name: PR Pipeline
on :
    workflow_dispatch:

jobs:
  read_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Logging in GitHub CLI
        run: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
            echo ${{ secrets.RELEASE_TOKEN }} | gh auth login -h GitHub.com -p https --with-token 
            gh auth status
       
        
      - name: Read repositories from file        
        run: |
          while IFS= read -r repo; do
            if [[ -n "$repo" && "$repo" != \#* ]]; then  
              echo "=== Procesando repo: $repo ==="

              # Verificar si las ramas existen
              BRANCHES=$(gh api "repos/${repo}/branches" --jq '.[].name' 2>/dev/null)
              if ! echo "$BRANCHES" | grep -q "develop" || ! echo "$BRANCHES" | grep -q "staging"; then
                echo "❌ El repo $repo no tiene las ramas 'develop' o 'staging'. Saltando..."
                continue
              fi

              echo "✅ Ramas verificadas. Creando PR..."
              gh pr create --repo "$repo" --base staging --head develop --title "Merge develop into staging" --body "Aprobado automáticamente con CI/CD"

              echo "Mezclando PR..."
              PR_NUMBER=$(gh pr list --repo "$repo" --json number --jq '.[0].number')
              gh pr merge "$PR_NUMBER" --repo "$repo" --admin --merge
            fi
          done < repos.txt

      - name: Deleting Token
        run: |
            gh logout

